language: csharp
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    dotnet: 1.0.0-preview2-003121
    env: DOTNETCORE=1
install: "apt-get install -qq -y luajit lua-cjson"
script:
- bash build.sh
